// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holdings.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createHoldingForUser = `-- name: CreateHoldingForUser :one
INSERT INTO holdings(id, user_id, stock_symbol, quantity, average_price, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    NOW(),
    NOW()
)
RETURNING id, user_id, stock_symbol, quantity, average_price, created_at, updated_at
`

type CreateHoldingForUserParams struct {
	UserID       uuid.NullUUID  `json:"user_id"`
	StockSymbol  sql.NullString `json:"stock_symbol"`
	Quantity     int32          `json:"quantity"`
	AveragePrice string         `json:"average_price"`
}

func (q *Queries) CreateHoldingForUser(ctx context.Context, arg CreateHoldingForUserParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, createHoldingForUser,
		arg.UserID,
		arg.StockSymbol,
		arg.Quantity,
		arg.AveragePrice,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StockSymbol,
		&i.Quantity,
		&i.AveragePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHoldingsOnSellOut = `-- name: DeleteHoldingsOnSellOut :execrows
DELETE FROM holdings 
WHERE holdings.user_id = $1 AND holdings.stock_symbol = $2
`

type DeleteHoldingsOnSellOutParams struct {
	UserID      uuid.NullUUID  `json:"user_id"`
	StockSymbol sql.NullString `json:"stock_symbol"`
}

func (q *Queries) DeleteHoldingsOnSellOut(ctx context.Context, arg DeleteHoldingsOnSellOutParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHoldingsOnSellOut, arg.UserID, arg.StockSymbol)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllHoldingsForUser = `-- name: GetAllHoldingsForUser :many
SELECT 
    holdings.stock_symbol AS stock_symbol,
    stocks.company_name AS company_name,
    holdings.quantity AS quantity,
    holdings.average_price AS average_price,
    stocks.current_price AS current_price,
    (holdings.quantity * stocks.current_price) AS current_value
FROM holdings
JOIN stocks
ON holdings.stock_symbol = stocks.symbol
WHERE holdings.user_id = $1
`

type GetAllHoldingsForUserRow struct {
	StockSymbol  sql.NullString `json:"stock_symbol"`
	CompanyName  string         `json:"company_name"`
	Quantity     int32          `json:"quantity"`
	AveragePrice string         `json:"average_price"`
	CurrentPrice string         `json:"current_price"`
	CurrentValue int32          `json:"current_value"`
}

func (q *Queries) GetAllHoldingsForUser(ctx context.Context, userID uuid.NullUUID) ([]GetAllHoldingsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllHoldingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllHoldingsForUserRow
	for rows.Next() {
		var i GetAllHoldingsForUserRow
		if err := rows.Scan(
			&i.StockSymbol,
			&i.CompanyName,
			&i.Quantity,
			&i.AveragePrice,
			&i.CurrentPrice,
			&i.CurrentValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHoldingByStockSymbol = `-- name: GetHoldingByStockSymbol :one
SELECT id, user_id, stock_symbol, quantity, average_price, created_at, updated_at FROM holdings
WHERE user_id = $1 AND stock_symbol = $2
`

type GetHoldingByStockSymbolParams struct {
	UserID      uuid.NullUUID  `json:"user_id"`
	StockSymbol sql.NullString `json:"stock_symbol"`
}

func (q *Queries) GetHoldingByStockSymbol(ctx context.Context, arg GetHoldingByStockSymbolParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, getHoldingByStockSymbol, arg.UserID, arg.StockSymbol)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StockSymbol,
		&i.Quantity,
		&i.AveragePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHoldingOnTransaction = `-- name: UpdateHoldingOnTransaction :one
UPDATE holdings
SET 
    quantity = $1,
    average_price = $2,
    updated_at = NOW()
WHERE user_id = $3 AND stock_symbol = $4
RETURNING id, user_id, stock_symbol, quantity, average_price, created_at, updated_at
`

type UpdateHoldingOnTransactionParams struct {
	Quantity     int32          `json:"quantity"`
	AveragePrice string         `json:"average_price"`
	UserID       uuid.NullUUID  `json:"user_id"`
	StockSymbol  sql.NullString `json:"stock_symbol"`
}

func (q *Queries) UpdateHoldingOnTransaction(ctx context.Context, arg UpdateHoldingOnTransactionParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, updateHoldingOnTransaction,
		arg.Quantity,
		arg.AveragePrice,
		arg.UserID,
		arg.StockSymbol,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StockSymbol,
		&i.Quantity,
		&i.AveragePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
