// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Holding struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	StockSymbol  sql.NullString `json:"stock_symbol"`
	Quantity     int32          `json:"quantity"`
	AveragePrice string         `json:"average_price"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Stock struct {
	Symbol        string         `json:"symbol"`
	CompanyName   string         `json:"company_name"`
	CurrentPrice  string         `json:"current_price"`
	PreviousClose sql.NullString `json:"previous_close"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Transaction struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.NullUUID  `json:"user_id"`
	StockSymbol sql.NullString `json:"stock_symbol"`
	Type        sql.NullString `json:"type"`
	Quantity    int32          `json:"quantity"`
	Price       string         `json:"price"`
	TotalAmount string         `json:"total_amount"`
	Fees        sql.NullString `json:"fees"`
	CreatedAt   time.Time      `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
