// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Holding struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	StockSymbol   string    `json:"stock_symbol"`
	Quantity      int32     `json:"quantity"`
	AveragePrice  float64   `json:"average_price"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	TotalInvested float64   `json:"total_invested"`
}

type Stock struct {
	Symbol        string          `json:"symbol"`
	CompanyName   string          `json:"company_name"`
	CurrentPrice  float64         `json:"current_price"`
	PreviousClose sql.NullFloat64 `json:"previous_close"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Transaction struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	StockSymbol string    `json:"stock_symbol"`
	Type        string    `json:"type"`
	Quantity    int32     `json:"quantity"`
	Price       float64   `json:"price"`
	TotalAmount float64   `json:"total_amount"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"created_at"`
	HashedPassword string    `json:"hashed_password"`
}
