version: '3.8'

services:
  postgres:
    image: postgres
    environment: 
      POSTGRES_DB: stonk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - stonks_db:/var/lib/postgresql/data
  
  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  stonks_db: